apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: magma
spec:
  selector:
    app: alertmanager
  ports:
    - name: tcp-9093
      protocol: TCP
      port: 9093
      targetPort: 9093

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: magma
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
              readOnly: true
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config

