apiVersion: v1
kind: Service
metadata:
  name: magma-controller-service
  namespace: magma
spec:
  selector:
    app: magma-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
  namespace: magma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: controller
          image: oakhmis/orc8r_controller
          env:
            - name: TEST_MODE
              value: "1"
            - name: SERVICE_HOSTNAME
              value: localhost
            - name: SQL_DRIVER
              value: postgres
            - name: DATABASE_SOURCE
              value: "dbname=magma_dev user=magma_dev password=magma_dev host=postgres-service sslmode=disable"
            - name: SQL_DIALECT
              value: psql
            - name: SERVICE_REGISTRY_MODE
              value: yaml
            - name: ORC8R_DOMAIN_NAME
              value: magma.test
            - name: VERSION_TAG
              value: LOCAL-DEV
            - name: HELM_VERSION_TAG
              value: LOCAL-DEV
            - name: MAGMA_PRINT_GRPC_PAYLOAD
              value: "0"
          volumeMounts:
            - name: magma-certs
              mountPath: /var/opt/magma/certs
            - name: supervisord-conf
              mountPath: /etc/supervisor/conf.d
          command:
            - "/bin/sh"
            - "-c"
            - "/usr/local/bin/wait-for-it.sh -s -t 30 postgres-service:5432 && /usr/bin/supervisord"
      restartPolicy: Always 
      volumes:
        - name: supervisord-conf
          configMap:
            name: controller-configmap
        - name: magma-certs
          hostPath:
            path: /var/opt/magma/certs
