apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: magma
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
  namespace: magma
spec:
  replicas: 1
  serviceName: kibana
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.3.1
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
  volumeClaimTemplates:
    - metadata:
        name: kibana-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
