apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: magma
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: magma
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: magma
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-deployment
  namespace: magma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: magma
            - name: MYSQL_DATABASE
              value: magma_dev
            - name: MYSQL_USER
              value: magma_dev
            - name: MYSQL_PASSWORD
              value: magma_dev
            - name: SQL_MODE
              value: ANSI_QUOTES
          args: ["mysqld"]
          args: ["--sql_mode=ANSI_QUOTES"]
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
