apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: magma
spec:
  ports:
    - name: controller-grpc
      port: 7443
      targetPort: 8443
    - name: bootstrapper
      port: 7444
      targetPort: 8444
    - name: api
      port: 9443
      targetPort: 9443
  selector:
    app: nginx





---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: magma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: magma-certs
          hostPath:
            path: /home/oussama/magma/orc8r/cloud/docker/.cache/test_certs
      containers:
        - name: nginx
          image: oakhmis/orc8r_nginx
          ports:
            - containerPort: 7443
            - containerPort: 7444
            - containerPort: 9443
          volumeMounts:
            - name: magma-certs
              mountPath: /var/opt/magma/certs
          env:
            - name: CONTROLLER_HOSTNAME
              value: controller.magma.test
            - name: PROXY_BACKENDS
              value: magma-controller-service
            - name: TEST_MODE
              value: "1"
            - name: RESOLVER
              value: 127.0.0.11
            - name: SERVICE_REGISTRY_MODE
              value: k8s
            - name: SSL_CERTIFICATE
              value: "/var/opt/magma/certs/controller.crt"
            - name: SSL_CERTIFICATE_KEY
              value: "/var/opt/magma/certs/controller.key"
            - name: SSL_CLIENT_CERTIFICATE
              value: "/var/opt/magma/certs/certifier.pem"
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
      restartPolicy: Always
