apiVersion: v1
kind: Service
metadata:
  name: fluentd-forward-service
  namespace: magma
spec:
  selector:
    app: fluentd-forward
  ports:
    - name: tcp-port
      protocol: TCP
      port: 24224
      targetPort: 24224
    - name: udp-port
      protocol: UDP
      port: 24224
      targetPort: 24224


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-forward-deployment
  namespace: magma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-forward
  template:
    metadata:
      labels:
        app: fluentd-forward
    spec:
      containers:
        - name: fluentd-forward
          image: oakhmis/fluentd_forward-image
          ports:
            - containerPort: 24224
              protocol: TCP
            - containerPort: 24224
              protocol: UDP


