apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: magma
spec:
  selector:
    app: thanos-query
  ports:
    - name: tcp-19192
      protocol: TCP
      port: 19192
      targetPort: 19192

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: magma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
        - name: thanos-query
          image: thanosio/thanos:master-2020-09-30-e4941a5c
          args:
            - "query"
            - "--http-address=0.0.0.0:19192"
            - "--store=thanosSidecar:19090"
            - "--store=thanosStore:10901"
          ports:
            - containerPort: 19192
