apiVersion: v1
kind: Service
metadata:
  name: thanos-store-service
  namespace: magma
spec:
  selector:
    app: thanos-store
  ports:
    - name: tcp-10901
      protocol: TCP
      port: 10901
      targetPort: 10901
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  namespace: magma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
        - name: thanos-store
          image: thanosio/thanos:master-2020-09-30-e4941a5c
          args:
            - "store"
            - "--objstore.config-file=/etc/thanos/objstore.yml"
          ports:
            - containerPort: 10901
          volumeMounts:
            - name: thanos-config
              mountPath: /etc/thanos
      volumes:
        - name: thanos-config
          configMap:
            name: thanos-config
